name: 'Setup Binaryen'
description: 'Install Binaryen WebAssembly toolchain'
inputs:
  version:
    description: 'Binaryen version to install'
    required: false
    default: '124'
  install-path:
    description: 'Directory to install Binaryen to'
    required: false
    default: '/opt/binaryen'

outputs:
  binaryen-path:
    description: 'Path to the installed Binaryen'
    value: ${{ steps.install-unix.outputs.binaryen-path || steps.install-windows.outputs.binaryen-path }}
  binaryen-version:
    description: 'Version of Binaryen that was installed'
    value: ${{ inputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Detect platform
      id: platform
      shell: bash
      run: |
        case "$RUNNER_OS" in
          Linux)
            echo "os=linux" >> $GITHUB_OUTPUT
            ;;
          macOS)
            echo "os=macos" >> $GITHUB_OUTPUT
            ;;
          Windows)
            echo "os=windows" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Unsupported OS: $RUNNER_OS"
            exit 1
            ;;
        esac

        case "$RUNNER_ARCH" in
          X64)
            if [ "$RUNNER_OS" = "Linux" ]; then
              echo "arch=x86_64" >> $GITHUB_OUTPUT
            else
              echo "arch=x86_64" >> $GITHUB_OUTPUT
            fi
            ;;
          ARM64)
            if [ "$RUNNER_OS" = "Linux" ]; then
              echo "arch=aarch64" >> $GITHUB_OUTPUT
            else
              echo "arch=arm64" >> $GITHUB_OUTPUT
            fi
            ;;
          *)
            echo "Unsupported architecture: $RUNNER_ARCH"
            exit 1
            ;;
        esac

    - name: Download and install Binaryen (Unix)
      id: install-unix
      if: runner.os != 'Windows'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        INSTALL_PATH: ${{ inputs.install-path }}
        OS: ${{ steps.platform.outputs.os }}
        ARCH: ${{ steps.platform.outputs.arch }}
      run: |
        TARBALL="binaryen-version_${VERSION}-${ARCH}-${OS}.tar.gz"
        URL="https://github.com/WebAssembly/binaryen/releases/download/version_${VERSION}/${TARBALL}"

        echo "Downloading Binaryen ${VERSION} for ${ARCH}-${OS}"
        echo "URL: ${URL}"

        curl -L -o binaryen.tar.gz "${URL}"

        mkdir -p "${INSTALL_PATH}"
        tar -xzf binaryen.tar.gz -C "${INSTALL_PATH}" --strip-components=1
        rm binaryen.tar.gz

        echo "binaryen-path=${INSTALL_PATH}" >> $GITHUB_OUTPUT
        echo "${INSTALL_PATH}/bin" >> $GITHUB_PATH

        echo "Binaryen installed to ${INSTALL_PATH}"

    - name: Download and install Binaryen (Windows)
      id: install-windows
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        VERSION: ${{ inputs.version }}
        INSTALL_PATH: ${{ inputs.install-path }}
        OS: ${{ steps.platform.outputs.os }}
        ARCH: ${{ steps.platform.outputs.arch }}
      run: |
        $TARBALL = "binaryen-version_$env:VERSION-$env:ARCH-$env:OS.tar.gz"
        $URL = "https://github.com/WebAssembly/binaryen/releases/download/version_$env:VERSION/$TARBALL"

        Write-Host "Downloading Binaryen $env:VERSION for $env:ARCH-$env:OS"
        Write-Host "URL: $URL"

        Invoke-WebRequest -Uri $URL -OutFile binaryen.tar.gz

        New-Item -ItemType Directory -Force -Path $env:INSTALL_PATH | Out-Null
        tar -xzf binaryen.tar.gz -C $env:INSTALL_PATH --strip-components=1
        Remove-Item binaryen.tar.gz

        Write-Output "binaryen-path=$env:INSTALL_PATH" >> $env:GITHUB_OUTPUT
        Write-Output "$env:INSTALL_PATH\bin" >> $env:GITHUB_PATH

        Write-Host "Binaryen installed to $env:INSTALL_PATH"

    - name: Verify installation (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        wasm-opt --version
        echo "Binaryen installation verified"

    - name: Verify installation (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        & wasm-opt --version
        Write-Host "Binaryen installation verified"
