using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace HakoJS.SourceGenerator;

public partial class JSBindingGenerator
{
    #region Object Binding Generation

    private static string GenerateObjectBinding(ObjectModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using HakoJS.VM;");
        sb.AppendLine("using HakoJS.Extensions;");
        sb.AppendLine("using HakoJS.SourceGeneration;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.SourceNamespace)) sb.AppendLine($"namespace {model.SourceNamespace};");

        sb.AppendLine();

        var hasDelegates = model.Parameters.Any(p => p.IsDelegate);
        var implementsDisposable = hasDelegates ? ", global::System.IDisposable" : "";

        sb.AppendLine(
            $"partial record {model.TypeName} : global::HakoJS.SourceGeneration.IJSMarshalable<{model.TypeName}>, global::HakoJS.SourceGeneration.IDefinitelyTyped<{model.TypeName}>{implementsDisposable}");
        sb.AppendLine("{");

        if (hasDelegates)
        {
            foreach (var param in model.Parameters.Where(p => p.IsDelegate))
                sb.AppendLine($"    private global::HakoJS.VM.JSValue? _captured{ToPascalCase(param.Name)};");

            sb.AppendLine();
        }

        GenerateObjectToJSValue(sb, model);
        sb.AppendLine();
        GenerateObjectFromJSValue(sb, model);

        if (hasDelegates)
        {
            sb.AppendLine();
            GenerateObjectDispose(sb, model);
        }

        sb.AppendLine();
        sb.AppendLine("    public static string TypeDefinition");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        var escapedTypeScript = model.TypeScriptDefinition.Replace("\"", "\"\"");
        sb.AppendLine("            return @\"");
        sb.Append(escapedTypeScript);
        sb.AppendLine("\";");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateObjectToJSValue(StringBuilder sb, ObjectModel model)
    {
        sb.AppendLine("    public global::HakoJS.VM.JSValue ToJSValue(global::HakoJS.VM.Realm realm)");
        sb.AppendLine("    {");
        sb.AppendLine("        var obj = realm.NewObject();");
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        foreach (var param in model.Parameters)
            if (param.IsDelegate && param.DelegateInfo != null)
            {
                GenerateDelegateToFunction(sb, param, "            ");
            }
            else
            {
                if (param.TypeInfo.IsNullable && !param.TypeInfo.IsValueType)
                {
                    sb.AppendLine($"            if ({param.Name} != null)");
                    sb.AppendLine(
                        $"                obj.SetProperty(\"{param.JsName}\", {GetMarshalCode(param.TypeInfo, param.Name, "realm")});");
                }
                else
                {
                    sb.AppendLine(
                        $"            obj.SetProperty(\"{param.JsName}\", {GetMarshalCode(param.TypeInfo, param.Name, "realm")});");
                }
            }

        sb.AppendLine("            return obj;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch");
        sb.AppendLine("        {");
        sb.AppendLine("            obj.Dispose();");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void GenerateDelegateToFunction(StringBuilder sb, RecordParameterModel param, string indent)
    {
        var delegateInfo = param.DelegateInfo!;
        var funcType = delegateInfo.IsAsync ? "NewFunctionAsync" : "NewFunction";

        if (param.TypeInfo.IsNullable && !param.TypeInfo.IsValueType)
        {
            sb.AppendLine($"{indent}if ({param.Name} != null)");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        var asyncPrefix = delegateInfo.IsAsync ? "async " : "";
        sb.AppendLine(
            $"{indent}using var {param.Name}Func = realm.{funcType}(\"{param.JsName}\", {asyncPrefix}(ctx, thisArg, args) =>");
        sb.AppendLine($"{indent}{{");

        var requiredParams = delegateInfo.Parameters.Count(p => !p.IsOptional);
        if (requiredParams > 0)
        {
            sb.AppendLine($"{indent}    if (args.Length < {requiredParams})");

            sb.AppendLine(
                $"{indent}        return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"{param.JsName}() requires at least {requiredParams} argument(s)\");");
            sb.AppendLine();
        }

        sb.AppendLine($"{indent}    try");
        sb.AppendLine($"{indent}    {{");

        for (var i = 0; i < delegateInfo.Parameters.Count; i++)
        {
            var p = delegateInfo.Parameters[i];
            var argName = $"args[{i}]";
            var varName = p.Name;

            if (p.IsOptional)
            {
                sb.AppendLine(
                    $"{indent}        var {varName} = args.Length > {i} ? {GetUnmarshalWithDefault(p.TypeInfo, argName, p.DefaultValue)} : {p.DefaultValue ?? GetDefaultValueForType(p.TypeInfo)};");
            }
            else
            {
                sb.AppendLine($"{indent}        if ({argName}.IsNullOrUndefined())");
                sb.AppendLine(
                    $"{indent}            return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{varName}' cannot be null or undefined\");");
                sb.AppendLine($"{indent}        if (!{GetTypeCheck(p.TypeInfo, argName)})");
                sb.AppendLine(
                    $"{indent}            return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{varName}' must be {GetTypeName(p.TypeInfo)}\");");
                sb.AppendLine($"{indent}        var {varName} = {GetStrictUnmarshalCode(p.TypeInfo, argName)};");
            }
        }

        var callArgs = string.Join(", ", delegateInfo.Parameters.Select(p => p.Name));

        if (delegateInfo.IsAsync)
        {
            if (!delegateInfo.IsVoid)
            {
                sb.AppendLine($"{indent}        var result = await {param.Name}({callArgs});");
                sb.AppendLine($"{indent}        return {GetMarshalCode(delegateInfo.ReturnType, "result", "ctx")};");
            }
            else
            {
                sb.AppendLine($"{indent}        await {param.Name}({callArgs});");
                sb.AppendLine($"{indent}        return ctx.Undefined();");
            }
        }
        else
        {
            if (!delegateInfo.IsVoid)
            {
                sb.AppendLine($"{indent}        var result = {param.Name}({callArgs});");
                sb.AppendLine($"{indent}        return {GetMarshalCode(delegateInfo.ReturnType, "result", "ctx")};");
            }
            else
            {
                sb.AppendLine($"{indent}        {param.Name}({callArgs});");
                sb.AppendLine($"{indent}        return ctx.Undefined();");
            }
        }

        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}    catch (global::System.Exception ex)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return ctx.ThrowError(ex);");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}});");
        sb.AppendLine($"{indent}obj.SetProperty(\"{param.JsName}\", {param.Name}Func);");

        if (param.TypeInfo.IsNullable && !param.TypeInfo.IsValueType)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void GenerateObjectFromJSValue(StringBuilder sb, ObjectModel model)
    {
        sb.AppendLine(
            $"    public static {model.TypeName} FromJSValue(global::HakoJS.VM.Realm realm, global::HakoJS.VM.JSValue jsValue)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!jsValue.IsObject())");
        sb.AppendLine("            throw new global::System.InvalidOperationException(\"JSValue must be an object\");");
        sb.AppendLine();

        var delegateParams = model.Parameters.Where(p => p.IsDelegate).ToList();
        if (delegateParams.Any())
        {
            foreach (var param in delegateParams)
                sb.AppendLine($"        global::HakoJS.VM.JSValue? captured{ToPascalCase(param.Name)} = null;");

            sb.AppendLine();
        }

        foreach (var param in model.Parameters)
        {
            if (param.IsDelegate && param.DelegateInfo != null)
                GenerateFunctionToDelegate(sb, param, "        ");
            else
                GenerateObjectPropertyUnmarshaling(sb, param, "        ");

            sb.AppendLine();
        }

        var constructorArgs = string.Join(", ", model.Parameters.Select(p => ToCamelCase(p.Name)));
        sb.AppendLine($"        var instance = new {model.TypeName}({constructorArgs});");

        if (delegateParams.Any())
        {
            sb.AppendLine();
            foreach (var param in delegateParams)
                sb.AppendLine(
                    $"        instance._captured{ToPascalCase(param.Name)} = captured{ToPascalCase(param.Name)};");
        }

        sb.AppendLine();
        sb.AppendLine("        return instance;");
        sb.AppendLine("    }");
    }

    private static void GenerateFunctionToDelegate(StringBuilder sb, RecordParameterModel param, string indent)
    {
        var delegateInfo = param.DelegateInfo!;
        var isRequired = !param.IsOptional;
        var propVarName = ToCamelCase(param.Name) + "Prop";
        var localVarName = ToCamelCase(param.Name);

        sb.AppendLine($"{indent}using var {propVarName} = jsValue.GetProperty(\"{param.JsName}\");");

        if (isRequired)
        {
            sb.AppendLine($"{indent}if ({propVarName}.IsNullOrUndefined())");
            sb.AppendLine(
                $"{indent}    throw new global::System.InvalidOperationException(\"Required property '{param.JsName}' is missing\");");
            sb.AppendLine($"{indent}if (!{propVarName}.IsFunction())");
            sb.AppendLine(
                $"{indent}    throw new global::System.InvalidOperationException(\"Property '{param.JsName}' must be a function\");");
            sb.AppendLine();

            sb.AppendLine($"{indent}captured{ToPascalCase(param.Name)} = {propVarName}.Dup();");
            GenerateDelegateWrapper(sb, param, $"{indent}var {localVarName} = ", ";");
        }
        else
        {
            sb.AppendLine($"{indent}{param.TypeInfo.FullName} {localVarName};");
            sb.AppendLine($"{indent}if ({propVarName}.IsNullOrUndefined())");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    {localVarName} = {param.DefaultValue ?? "null"};");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    if (!{propVarName}.IsFunction())");
            sb.AppendLine(
                $"{indent}        throw new global::System.InvalidOperationException(\"Property '{param.JsName}' must be a function\");");
            sb.AppendLine();
            sb.AppendLine($"{indent}    captured{ToPascalCase(param.Name)} = {propVarName}.Dup();");
            GenerateDelegateWrapper(sb, param, $"{indent}    {localVarName} = ", ";");
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void GenerateDelegateWrapper(StringBuilder sb, RecordParameterModel param, string prefix,
        string suffix)
    {
        var delegateInfo = param.DelegateInfo!;
        var indent = new string(' ', prefix.Length);

        var paramTypes = string.Join(", ", delegateInfo.Parameters.Select(p => p.TypeInfo.FullName));

        string delegateType;
        if (delegateInfo.IsVoid)
        {
            delegateType = paramTypes.Length > 0
                ? $"global::System.Action<{paramTypes}>"
                : "global::System.Action";
        }
        else
        {
            var returnTypeStr = delegateInfo.IsAsync
                ? $"global::System.Threading.Tasks.Task<{delegateInfo.ReturnType.FullName}>"
                : delegateInfo.ReturnType.FullName;

            delegateType = paramTypes.Length > 0
                ? $"global::System.Func<{paramTypes}, {returnTypeStr}>"
                : $"global::System.Func<{returnTypeStr}>";
        }

        var delegateParams = string.Join(", ", delegateInfo.Parameters.Select(p => $"{p.TypeInfo.FullName} {p.Name}"));

        if (delegateInfo.IsAsync)
        {
            sb.Append($"{prefix}new {delegateType}(async ({delegateParams}) =>");
            sb.AppendLine();
            sb.AppendLine($"{indent}{{");

            foreach (var p in delegateInfo.Parameters)
                sb.AppendLine($"{indent}    using var {p.Name}Js = realm.NewValue({p.Name});");

            var jsArgs = string.Join(", ", delegateInfo.Parameters.Select(p => $"{p.Name}Js"));
            if (jsArgs.Length > 0)
                sb.AppendLine(
                    $"{indent}    using var result = realm.CallFunction(captured{ToPascalCase(param.Name)}!, null, {jsArgs}).Unwrap();");
            else
                sb.AppendLine(
                    $"{indent}    using var result = realm.CallFunction(captured{ToPascalCase(param.Name)}!, null).Unwrap();");

            sb.AppendLine();

            if (!delegateInfo.IsVoid)
            {
                sb.AppendLine($"{indent}    using var awaited = await result.Await();");
                sb.AppendLine($"{indent}    return {GetUnmarshalCode(delegateInfo.ReturnType, "awaited")};");
            }
            else
            {
                sb.AppendLine($"{indent}    await result.Await();");
            }

            sb.Append($"{indent}}})");
            sb.AppendLine(suffix);
        }
        else
        {
            sb.Append($"{prefix}new {delegateType}(({delegateParams}) =>");
            sb.AppendLine();
            sb.AppendLine($"{indent}{{");

            foreach (var p in delegateInfo.Parameters)
                sb.AppendLine($"{indent}    using var {p.Name}Js = realm.NewValue({p.Name});");

            var jsArgs = string.Join(", ", delegateInfo.Parameters.Select(p => $"{p.Name}Js"));
            if (jsArgs.Length > 0)
                sb.AppendLine(
                    $"{indent}    using var result = realm.CallFunction(captured{ToPascalCase(param.Name)}!, null, {jsArgs}).Unwrap();");
            else
                sb.AppendLine(
                    $"{indent}    using var result = realm.CallFunction(captured{ToPascalCase(param.Name)}!, null).Unwrap();");

            if (!delegateInfo.IsVoid)
                sb.AppendLine($"{indent}    return {GetUnmarshalCode(delegateInfo.ReturnType, "result")};");

            sb.Append($"{indent}}})");
            sb.AppendLine(suffix);
        }
    }

    private static void GenerateObjectPropertyUnmarshaling(StringBuilder sb, RecordParameterModel param, string indent)
    {
        var isRequired = !param.IsOptional;
        var propVarName = ToCamelCase(param.Name) + "Prop";
        var localVarName = ToCamelCase(param.Name);

        sb.AppendLine($"{indent}using var {propVarName} = jsValue.GetProperty(\"{param.JsName}\");");

        if (isRequired)
        {
            if (param.TypeInfo.IsNullable)
            {
                sb.AppendLine(
                    $"{indent}if (!{propVarName}.IsNullOrUndefined() && !{GetTypeCheck(param.TypeInfo, propVarName)})");
                sb.AppendLine(
                    $"{indent}    throw new global::System.InvalidOperationException(\"Property '{param.Name}' must be {GetTypeName(param.TypeInfo)}\");");
                sb.AppendLine(
                    $"{indent}var {localVarName} = {propVarName}.IsNullOrUndefined() ? null : {GetStrictUnmarshalCode(param.TypeInfo, propVarName, "realm")};");
            }
            else
            {
                sb.AppendLine($"{indent}if ({propVarName}.IsNullOrUndefined())");
                sb.AppendLine(
                    $"{indent}    throw new global::System.InvalidOperationException(\"Property '{param.Name}' cannot be null or undefined\");");
                sb.AppendLine($"{indent}if (!{GetTypeCheck(param.TypeInfo, propVarName)})");
                sb.AppendLine(
                    $"{indent}    throw new global::System.InvalidOperationException(\"Property '{param.Name}' must be {GetTypeName(param.TypeInfo)}\");");
                sb.AppendLine(
                    $"{indent}var {localVarName} = {GetStrictUnmarshalCode(param.TypeInfo, propVarName, "realm")};");
            }
        }
        else
        {
            sb.AppendLine($"{indent}{param.TypeInfo.FullName} {localVarName};");
            sb.AppendLine($"{indent}if ({propVarName}.IsNullOrUndefined())");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine(
                $"{indent}    {localVarName} = {param.DefaultValue ?? GetDefaultValueForType(param.TypeInfo)};");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    if (!{GetTypeCheck(param.TypeInfo, propVarName)})");
            sb.AppendLine(
                $"{indent}        throw new global::System.InvalidOperationException(\"Property '{param.Name}' must be {GetTypeName(param.TypeInfo)}\");");
            sb.AppendLine(
                $"{indent}    {localVarName} = {GetStrictUnmarshalCode(param.TypeInfo, propVarName, "realm")};");
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void GenerateObjectDispose(StringBuilder sb, ObjectModel model)
    {
        sb.AppendLine("    public void Dispose()");
        sb.AppendLine("    {");

        foreach (var param in model.Parameters.Where(p => p.IsDelegate))
        {
            sb.AppendLine($"        _captured{ToPascalCase(param.Name)}?.Dispose();");
            sb.AppendLine($"        _captured{ToPascalCase(param.Name)} = null;");
        }

        sb.AppendLine("    }");
    }

    #endregion

    #region Parameter Unmarshaling

    private static void GenerateParameterUnmarshaling(StringBuilder sb, ParameterModel param, int index, string indent)
    {
        var argName = $"args[{index}]";
        var isRequired = !param.IsOptional;
        var type = param.TypeInfo;

        if (type.UnderlyingType != null)
        {
            var underlyingTypeInfo = CreateTypeInfo(type.UnderlyingType);

            if (isRequired)
            {
                sb.AppendLine($"{indent}var arg{index}IsNull = {argName}.IsNullOrUndefined();");
                sb.AppendLine($"{indent}if (!arg{index}IsNull && !{GetTypeCheck(underlyingTypeInfo, argName)})");
                sb.AppendLine(
                    $"{indent}    return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{param.Name}' must be {GetTypeName(underlyingTypeInfo)}\");");
                sb.AppendLine(
                    $"{indent}var {param.Name} = arg{index}IsNull ? null : ({type.FullName})({GetStrictUnmarshalCode(underlyingTypeInfo, argName)});");
            }
            else
            {
                var defaultExpr = param.DefaultValue ?? "null";
                sb.AppendLine($"{indent}{type.FullName} {param.Name};");
                sb.AppendLine($"{indent}if (args.Length > {index})");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    var arg{index}IsNull = {argName}.IsNullOrUndefined();");
                sb.AppendLine($"{indent}    if (!arg{index}IsNull && !{GetTypeCheck(underlyingTypeInfo, argName)})");
                sb.AppendLine(
                    $"{indent}        return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{param.Name}' must be {GetTypeName(underlyingTypeInfo)}\");");
                sb.AppendLine(
                    $"{indent}    {param.Name} = arg{index}IsNull ? null : ({type.FullName})({GetStrictUnmarshalCode(underlyingTypeInfo, argName)});");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine($"{indent}else");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    {param.Name} = {defaultExpr};");
                sb.AppendLine($"{indent}}}");
            }
        }
        else if (isRequired)
        {
            if (type.IsNullable)
            {
                sb.AppendLine($"{indent}var arg{index}IsNull = {argName}.IsNullOrUndefined();");
                sb.AppendLine($"{indent}if (!arg{index}IsNull && !{GetTypeCheck(type, argName)})");
                sb.AppendLine(
                    $"{indent}    return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{param.Name}' must be {GetTypeName(type)}\");");
                sb.AppendLine(
                    $"{indent}var {param.Name} = arg{index}IsNull ? null : {GetStrictUnmarshalCode(type, argName)};");
            }
            else
            {
                sb.AppendLine($"{indent}if ({argName}.IsNullOrUndefined())");
                sb.AppendLine(
                    $"{indent}    return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{param.Name}' cannot be null or undefined\");");
                sb.AppendLine($"{indent}if (!{GetTypeCheck(type, argName)})");
                sb.AppendLine(
                    $"{indent}    return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{param.Name}' must be {GetTypeName(type)}\");");
                sb.AppendLine($"{indent}var {param.Name} = {GetStrictUnmarshalCode(type, argName)};");
            }
        }
        else
        {
            var defaultExpr = param.DefaultValue ?? GetDefaultValueForType(type);

            if (type.IsNullable)
            {
                sb.AppendLine($"{indent}{type.FullName} {param.Name};");
                sb.AppendLine($"{indent}if (args.Length > {index})");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    var arg{index}IsNull = {argName}.IsNullOrUndefined();");
                sb.AppendLine($"{indent}    if (!arg{index}IsNull && !{GetTypeCheck(type, argName)})");
                sb.AppendLine(
                    $"{indent}        return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{param.Name}' must be {GetTypeName(type)}\");");
                sb.AppendLine(
                    $"{indent}    {param.Name} = arg{index}IsNull ? null : {GetStrictUnmarshalCode(type, argName)};");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine($"{indent}else");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    {param.Name} = {defaultExpr};");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                sb.AppendLine($"{indent}{type.FullName} {param.Name};");
                sb.AppendLine($"{indent}if (args.Length > {index})");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    if ({argName}.IsNullOrUndefined())");
                sb.AppendLine(
                    $"{indent}        return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{param.Name}' cannot be null or undefined\");");
                sb.AppendLine($"{indent}    if (!{GetTypeCheck(type, argName)})");
                sb.AppendLine(
                    $"{indent}        return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Parameter '{param.Name}' must be {GetTypeName(type)}\");");
                sb.AppendLine($"{indent}    {param.Name} = {GetStrictUnmarshalCode(type, argName)};");
                sb.AppendLine($"{indent}}}");
                sb.AppendLine($"{indent}else");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    {param.Name} = {defaultExpr};");
                sb.AppendLine($"{indent}}}");
            }
        }
    }

    private static void GenerateValueUnmarshaling(StringBuilder sb, TypeInfo type, string varName, string jsValueName,
        string indent)
    {
        if (type.UnderlyingType != null)
        {
            var underlyingTypeInfo = CreateTypeInfo(type.UnderlyingType);
            sb.AppendLine(
                $"{indent}if (!{jsValueName}.IsNullOrUndefined() && !{GetTypeCheck(underlyingTypeInfo, jsValueName)})");
            sb.AppendLine(
                $"{indent}    return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Value '{varName}' must be {GetTypeName(underlyingTypeInfo)}\");");
            sb.AppendLine(
                $"{indent}var {varName} = {jsValueName}.IsNullOrUndefined() ? null : ({type.FullName})({GetStrictUnmarshalCode(underlyingTypeInfo, jsValueName)});");
        }
        else if (type.IsNullable)
        {
            sb.AppendLine($"{indent}if (!{jsValueName}.IsNullOrUndefined() && !{GetTypeCheck(type, jsValueName)})");
            sb.AppendLine(
                $"{indent}    return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Value '{varName}' must be {GetTypeName(type)}\");");
            sb.AppendLine(
                $"{indent}var {varName} = {jsValueName}.IsNullOrUndefined() ? null : {GetStrictUnmarshalCode(type, jsValueName)};");
        }
        else
        {
            sb.AppendLine($"{indent}if ({jsValueName}.IsNullOrUndefined())");
            sb.AppendLine(
                $"{indent}    return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Value '{varName}' cannot be null or undefined\");");
            sb.AppendLine($"{indent}if (!{GetTypeCheck(type, jsValueName)})");
            sb.AppendLine(
                $"{indent}    return ctx.ThrowError(global::HakoJS.VM.JSErrorType.Type, \"Value '{varName}' must be {GetTypeName(type)}\");");
            sb.AppendLine($"{indent}var {varName} = {GetStrictUnmarshalCode(type, jsValueName)};");
        }
    }

    #endregion

    #region Marshaling Helpers

    private static string GetTypeCheck(TypeInfo type, string jsValueName)
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_String:
                return $"{jsValueName}.IsString()";
            case SpecialType.System_Boolean:
                return $"{jsValueName}.IsBoolean()";
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
            case SpecialType.System_Int16:
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_UInt32:
            case SpecialType.System_UInt64:
            case SpecialType.System_UInt16:
            case SpecialType.System_Double:
            case SpecialType.System_Single:
                return $"{jsValueName}.IsNumber()";
            case SpecialType.System_DateTime:
                return $"{jsValueName}.IsDate()";
        }

        // Handle [JSEnum]
        if (type.IsEnum)
            return type.IsFlags
                ? $"{jsValueName}.IsNumber()"
                : $"{jsValueName}.IsString()";

        if (type.FullName == "global::System.Byte[]")
            return $"({jsValueName}.IsArrayBuffer() || {jsValueName}.IsTypedArray())";

        if (type.IsArray)
            return $"{jsValueName}.IsArray()";

        return $"{jsValueName}.IsObject()";
    }

    private static string GetStrictUnmarshalCode(TypeInfo type, string jsValueName, string contextVarName = "ctx")
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_String:
                return $"{jsValueName}.AsString()";
            case SpecialType.System_Int32:
                return $"(int){jsValueName}.AsNumber()";
            case SpecialType.System_Int64:
                return $"(long){jsValueName}.AsNumber()";
            case SpecialType.System_Double:
                return $"{jsValueName}.AsNumber()";
            case SpecialType.System_Single:
                return $"(float){jsValueName}.AsNumber()";
            case SpecialType.System_Boolean:
                return $"{jsValueName}.AsBoolean()";
            case SpecialType.System_Int16:
                return $"(short){jsValueName}.AsNumber()";
            case SpecialType.System_Byte:
                return $"(byte){jsValueName}.AsNumber()";
            case SpecialType.System_SByte:
                return $"(sbyte){jsValueName}.AsNumber()";
            case SpecialType.System_UInt32:
                return $"(uint){jsValueName}.AsNumber()";
            case SpecialType.System_UInt64:
                return $"(ulong){jsValueName}.AsNumber()";
            case SpecialType.System_UInt16:
                return $"(ushort){jsValueName}.AsNumber()";
            case SpecialType.System_DateTime:
                return $"{jsValueName}.AsDateTime()";
        }

        if (type.IsEnum)
        {
            if (type.IsFlags) return $"({type.FullName})(int){jsValueName}.AsNumber()";

            return $"global::System.Enum.Parse<{type.FullName}>({jsValueName}.AsString(), ignoreCase: true)";
        }

        if (type.FullName == "global::System.Byte[]")
            return
                $"({jsValueName}.IsArrayBuffer() ? {jsValueName}.CopyArrayBuffer() : {jsValueName}.CopyTypedArray())";

        if (type is { IsArray: true, ElementType: not null })
        {
            if (IsPrimitiveTypeName(type.ElementType)) return $"{jsValueName}.ToArray<{type.ElementType}>()";

            return $"{jsValueName}.ToArrayOf<{type.ElementType}>()";
        }

        return $"{type.FullName}.FromJSValue({contextVarName}, {jsValueName})";
    }

    private static string GetUnmarshalCode(TypeInfo type, string jsValueName, string contextVarName = "realm")
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_String:
                return $"{jsValueName}.AsString()";
            case SpecialType.System_Int32:
                return $"(int){jsValueName}.AsNumber()";
            case SpecialType.System_Int64:
                return $"(long){jsValueName}.AsNumber()";
            case SpecialType.System_Double:
                return $"{jsValueName}.AsNumber()";
            case SpecialType.System_Single:
                return $"(float){jsValueName}.AsNumber()";
            case SpecialType.System_Boolean:
                return $"{jsValueName}.AsBoolean()";
            case SpecialType.System_Int16:
                return $"(short){jsValueName}.AsNumber()";
            case SpecialType.System_Byte:
                return $"(byte){jsValueName}.AsNumber()";
            case SpecialType.System_SByte:
                return $"(sbyte){jsValueName}.AsNumber()";
            case SpecialType.System_UInt32:
                return $"(uint){jsValueName}.AsNumber()";
            case SpecialType.System_UInt64:
                return $"(ulong){jsValueName}.AsNumber()";
            case SpecialType.System_UInt16:
                return $"(ushort){jsValueName}.AsNumber()";
            case SpecialType.System_DateTime:
                return $"{jsValueName}.AsDateTime()";
        }

        if (type.FullName == "global::System.Byte[]")
            return
                $"({jsValueName}.IsArrayBuffer() ? {jsValueName}.CopyArrayBuffer() : {jsValueName}.CopyTypedArray())";

        return $"{type.FullName}.FromJSValue({contextVarName}, {jsValueName})";
    }

    private static string GetUnmarshalWithDefault(TypeInfo type, string jsValueName, string? defaultValue)
    {
        var unmarshalCode = GetStrictUnmarshalCode(type, jsValueName);
        var defaultExpr = defaultValue ?? GetDefaultValueForType(type);

        if (type.IsNullable) return $"{jsValueName}.IsNullOrUndefined() ? {defaultExpr} : {unmarshalCode}";

        return
            $"!{jsValueName}.IsNullOrUndefined() && {GetTypeCheck(type, jsValueName)} ? {unmarshalCode} : {defaultExpr}";
    }

    private static string GetTypeName(TypeInfo type)
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_String:
                return "a string";
            case SpecialType.System_Boolean:
                return "a boolean";
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
            case SpecialType.System_Int16:
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_UInt32:
            case SpecialType.System_UInt64:
            case SpecialType.System_UInt16:
            case SpecialType.System_Double:
            case SpecialType.System_Single:
                return "a number";
            case SpecialType.System_DateTime:
                return "a Date";
        }

        // Handle [JSEnum]
        if (type.IsEnum) return type.IsFlags ? "a number (flags enum)" : "a string (enum)";

        if (type.FullName == "global::System.Byte[]")
            return "an ArrayBuffer or TypedArray";

        if (type.IsArray)
            return "an array";

        return "an object";
    }

    private static string GetMarshalCode(TypeInfo type, string valueName, string ctxName)
    {
        if (type.UnderlyingType != null)
        {
            var underlyingTypeInfo = CreateTypeInfo(type.UnderlyingType);
            var underlyingMarshalCode = GetMarshalCodeForPrimitive(underlyingTypeInfo, valueName, ctxName);
            return
                $"({valueName}.HasValue ? {underlyingMarshalCode.Replace(valueName, $"{valueName}.Value")} : {ctxName}.Null())";
        }

        return GetMarshalCodeForPrimitive(type, valueName, ctxName);
    }

    private static string GetMarshalCodeForPrimitive(TypeInfo type, string valueName, string ctxName)
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_String:
                return type.IsNullable
                    ? $"({valueName} == null ? {ctxName}.Null() : {ctxName}.NewString({valueName}))"
                    : $"{ctxName}.NewString({valueName})";
            case SpecialType.System_Boolean:
                return $"({valueName} ? {ctxName}.True() : {ctxName}.False())";
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
            case SpecialType.System_Int16:
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_UInt32:
            case SpecialType.System_UInt64:
            case SpecialType.System_UInt16:
                return $"{ctxName}.NewNumber({valueName})";
            case SpecialType.System_Double:
            case SpecialType.System_Single:
                return
                    $"{ctxName}.NewNumber(double.IsNaN({valueName}) || double.IsInfinity({valueName}) ? 0.0 : {valueName})";
            case SpecialType.System_Void:
                return $"{ctxName}.Undefined()";

            case SpecialType.System_DateTime:
                return type.IsNullable
                    ? $"({valueName}.HasValue ? {ctxName}.NewDate({valueName}.Value) : {ctxName}.Null())"
                    : $"{ctxName}.NewDate({valueName})";
        }

        if (type.IsEnum)
        {
            if (type.IsFlags)
                return type.IsNullable
                    ? $"({valueName} == null ? {ctxName}.Null() : {ctxName}.NewNumber((int){valueName}))"
                    : $"{ctxName}.NewNumber((int){valueName})";

            return type.IsNullable
                ? $"({valueName} == null ? {ctxName}.Null() : {ctxName}.NewString({valueName}.ToString()))"
                : $"{ctxName}.NewString({valueName}.ToString())";
        }

        if (type.FullName == "global::System.Byte[]")
            return type.IsNullable
                ? $"({valueName} == null ? {ctxName}.Null() : {ctxName}.NewArrayBuffer({valueName}))"
                : $"{ctxName}.NewArrayBuffer({valueName})";

        if (type is { IsArray: true, ElementType: not null })
        {
            if (IsPrimitiveTypeName(type.ElementType))
                return type.IsNullable
                    ? $"({valueName} == null ? {ctxName}.Null() : {valueName}.ToJSArray({ctxName}))"
                    : $"{valueName}.ToJSArray({ctxName})";

            return type.IsNullable
                ? $"({valueName} == null ? {ctxName}.Null() : {valueName}.ToJSArrayOf({ctxName}))"
                : $"{valueName}.ToJSArrayOf({ctxName})";
        }

        if (!type.IsValueType || type.IsNullable)
            return $"({valueName} == null ? {ctxName}.Null() : {valueName}.ToJSValue({ctxName}))";

        return $"{valueName}.ToJSValue({ctxName})";
    }

    private static string GetDefaultValueForType(TypeInfo type)
    {
        if (type.UnderlyingType != null)
            return "null";

        if (type is { IsNullable: true, IsValueType: false })
            return "null";

        return type.SpecialType switch
        {
            SpecialType.System_String => "string.Empty",
            SpecialType.System_Boolean => "false",
            SpecialType.System_Char => "'\\0'",
            SpecialType.System_Single => "0.0f",
            SpecialType.System_Double => "0.0",
            SpecialType.System_Decimal => "0.0m",
            SpecialType.System_Int32 or SpecialType.System_Int64 or SpecialType.System_Int16 or
                SpecialType.System_Byte or SpecialType.System_SByte or SpecialType.System_UInt32 or
                SpecialType.System_UInt64 or SpecialType.System_UInt16 => "0",
            _ => $"default({type.FullName})"
        };
    }

    #endregion
}